# CMake generated Testfile for 
# Source directory: /home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/test
# Build directory: /home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_octet_consistency "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_octet_consistency")
set_tests_properties(test_octet_consistency PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_version "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_version")
set_tests_properties(test_version PROPERTIES  PASS_REGULAR_EXPRESSION "Version: 2.0.1" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_utils "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_utils")
set_tests_properties(test_utils PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_hash_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_hash_256" "sha/256/SHA256ShortMsg.rsp" "sha256")
set_tests_properties(test_hash_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_hash_384 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_hash_384" "sha/384/SHA384ShortMsg.rsp" "sha384")
set_tests_properties(test_hash_384 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_hash_512 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_hash_512" "sha/512/SHA512ShortMsg.rsp" "sha512")
set_tests_properties(test_hash_512 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_gcm_encrypt_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_gcm_encrypt_128" "gcm/gcmEncryptExtIV128.rsp")
set_tests_properties(test_gcm_encrypt_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_gcm_encrypt_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_gcm_encrypt_256" "gcm/gcmEncryptExtIV256.rsp")
set_tests_properties(test_gcm_encrypt_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_gcm_decrypt_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_gcm_decrypt_128" "gcm/gcmDecrypt128.rsp")
set_tests_properties(test_gcm_decrypt_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_gcm_decrypt_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_gcm_decrypt_256" "gcm/gcmDecrypt256.rsp")
set_tests_properties(test_gcm_decrypt_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_ECB_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_ECB_128" "aes/ECBMMT128.rsp" "ECB")
set_tests_properties(test_aes_encrypt_ECB_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_ECB_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_ECB_256" "aes/ECBMMT256.rsp" "ECB")
set_tests_properties(test_aes_encrypt_ECB_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_CBC_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_CBC_128" "aes/CBCMMT128.rsp" "CBC")
set_tests_properties(test_aes_encrypt_CBC_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_CFB1_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_CFB1_128" "aes/CFB8MMT128.rsp" "CFB1")
set_tests_properties(test_aes_encrypt_CFB1_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_CBC_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_CBC_256" "aes/CBCMMT256.rsp" "CBC")
set_tests_properties(test_aes_encrypt_CBC_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_CTR_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_CTR_128" "aes/amcl_CTRMCL128.rsp" "CTR")
set_tests_properties(test_aes_encrypt_CTR_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_CTR_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_CTR_256" "aes/amcl_CTRMCL256.rsp" "CTR")
set_tests_properties(test_aes_encrypt_CTR_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_encrypt_CFB1_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_encrypt_CFB1_256" "aes/CFB8MMT256.rsp" "CFB1")
set_tests_properties(test_aes_encrypt_CFB1_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_ECB_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_ECB_128" "aes/ECBMMT128.rsp" "ECB")
set_tests_properties(test_aes_decrypt_ECB_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_ECB_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_ECB_256" "aes/ECBMMT256.rsp" "ECB")
set_tests_properties(test_aes_decrypt_ECB_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_CBC_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_CBC_128" "aes/CBCMMT128.rsp" "CBC")
set_tests_properties(test_aes_decrypt_CBC_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_CFB1_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_CFB1_128" "aes/CFB8MMT128.rsp" "CFB1")
set_tests_properties(test_aes_decrypt_CFB1_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_CBC_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_CBC_256" "aes/CBCMMT256.rsp" "CBC")
set_tests_properties(test_aes_decrypt_CBC_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_CTR_128 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_CTR_128" "aes/amcl_CTRMCL128.rsp" "CTR")
set_tests_properties(test_aes_decrypt_CTR_128 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_CTR_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_CTR_256" "aes/amcl_CTRMCL256.rsp" "CTR")
set_tests_properties(test_aes_decrypt_CTR_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_aes_decrypt_CFB1_256 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_aes_decrypt_CFB1_256" "aes/CFB8MMT256.rsp" "CFB1")
set_tests_properties(test_aes_decrypt_CFB1_256 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_big_arithmetics_1024_58 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_big_arithmetics_1024_58" "big/test_vector_big.txt")
set_tests_properties(test_big_arithmetics_1024_58 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_big_consistency_1024_58 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_big_consistency_1024_58")
set_tests_properties(test_big_consistency_1024_58 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_ff_consistency_2048 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_ff_consistency_2048")
set_tests_properties(test_ff_consistency_2048 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_big_arithmetics_512_60 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_big_arithmetics_512_60" "big/test_vector_big.txt")
set_tests_properties(test_big_arithmetics_512_60 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_big_consistency_512_60 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_big_consistency_512_60")
set_tests_properties(test_big_consistency_512_60 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_ff_consistency_4096 "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_ff_consistency_4096")
set_tests_properties(test_ff_consistency_4096 PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_paillier_consistency "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_paillier_consistency")
set_tests_properties(test_paillier_consistency PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_paillier_decrypt "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_paillier_decrypt" "paillier/decrypt.txt")
set_tests_properties(test_paillier_decrypt PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_paillier_encrypt "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_paillier_encrypt" "paillier/encrypt.txt")
set_tests_properties(test_paillier_encrypt PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_paillier_add "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_paillier_add" "paillier/add.txt")
set_tests_properties(test_paillier_add PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_paillier_mult "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_paillier_mult" "paillier/mult.txt")
set_tests_properties(test_paillier_mult PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
add_test(test_paillier_keygen "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/bin/test_paillier_keygen" "paillier/keygen.txt")
set_tests_properties(test_paillier_keygen PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" WORKING_DIRECTORY "/home/jrml/devel/lua-multiparty/lib/milagro-crypto-c/testVectors")
