name: Run Tests

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '*.md'
    branches:
      - master
      - github-actions

  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'
    branches:
      - master
      - github-actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  c-lint:
    name: 🚨 C lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-lint')"
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-cpplint@master
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          targets: --recursive src
          level: warning
          flags: --linelength=120 # Optional
          filter: "-readability/braces\
            ,-readability/casting\
            ,-readability/todo\
            ,-whitespace/comma\
            ,-whitespace/braces\
            ,-whitespace/comments\
            ,-whitespace/indent\
            ,-whitespace/newline\
            ,-whitespace/operators\
            ,-whitespace/parens\
            ,-whitespace/tab\
            ,-whitespace/end_of_line\
            ,-whitespace/line_length\
            ,-whitespace/blank_line\
            ,-whitespace/semicolon\
            ,-build/include_subdir\
            ,-build/include_order\
            "

  test-suite:
    name: 🔬 test
    needs: [c-lint]
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-test')"
    strategy:
      matrix:
        compiler: [gcc]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install --no-install-recommends -y ${{ matrix.compiler }} cmake lua5.1 liblua5.1-0-dev
      - name: ${{ matrix.compiler }} build
        run: |
          make
      - name: ${{ matrix.compiler }} run tests
        run: |
          make check
